webapp/user/models.py
from datetime import datetime
from flask_login import UserMixin
from webapp.db import db
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.Text, nullable=False, unique=True)
    password_hash = db.Column(db.Text, nullable=False)
    name = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    shopping_lists = db.relationship("ShoppingList", backref="user", lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return (
            f"User {self.id} "
            f"\nemail: {self.email} "
            f"\nname: {self.name}"
            f"\ncreated_at {self.created_at}"
        )

webapp/user/forms.py
from flask_wtf import FlaskForm
from webapp.user.models import User
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError


class RegistrationForm(FlaskForm):
    name = StringField(
        "Имя", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    email = StringField(
        "Адрес электронной почты",
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        "Пароль", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    password2 = PasswordField(
        "Повторите пароль",
        validators=[DataRequired(), EqualTo("password")],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField("Зарегистрироваться", render_kw={"class": "btn btn-primary"})

    def validate_email(self, email):
        users_count = User.query.filter_by(email=email.data.lower()).count()
        if users_count > 0:
            raise ValidationError("Пользователь с таким email уже существует")


class LoginForm(FlaskForm):
    email = StringField(
        "Адрес электронной почты",
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        "Пароль", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    submit = SubmitField("Войти", render_kw={"class": "btn btn-primary w-100 py-2"})

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import flash_errors_from_form

blueprint = Blueprint("user", __name__, url_prefix="/users")


@blueprint.route("/registration")
def registration():
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template(
        "user/registration.html",
        form=form,
        page_title=title,
    )


@blueprint.route("/process-reg", methods=["POST"])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        user_name = form.name.data
        if user_name.lower() == "admin":
            flash(
                "Регистрация под таким именем невозможна",
                category="danger",
            )
        else:
            user_email = form.email.data.lower()
            new_user = User(name=user_name, email=user_email)
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.commit()
            flash("Вы успешно зарегистрировались", category="success")
            return redirect(url_for("user.login"))

    else:
        flash_errors_from_form(form)
    return redirect(url_for("user.registration"))


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index"))

    form = LoginForm()
    email = form.email.data
    password = form.password.data

    if form.validate_on_submit():
        user = User.query.filter(User.email == email).one_or_none()
        if user:
            if user.check_password(password):
                login_user(user)
                flash("Вы успешно вошли на сайт", category="success")
                return redirect(url_for("index"))
            else:
                flash("Неверный пароль", category="danger")
        else:
            flash("Пользователь с таким email не зарегистрирован", category="danger")

    return render_template("user/login.html", form=form)


@blueprint.route("/profile")
@login_required
def profile():
    user = current_user
    title = "Моя страница"
    return render_template(
        "user/profile.html",
        page_title=title,
        user=user,
    )


@blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Вы успешно вышли из аккаунта", category="success")
    return redirect(url_for("index"))

webapp/templates/user/login.html
{% extends "base.html" %} {% block content %}
<div class="row">
  <div class="hidden-xs col-sm-1 col-md-3 col-lg-4"></div>
  <div class="col-xs-12 col-sm-10 col-md-6 col-lg-4 text-center">
    <div class="p-5"></div>
    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
      <form action="{{ url_for('user.login') }}" method="POST">
        {{ form.hidden_tag() }}

        <h1 class="h3 mb-3 fw-normal">Вход на сайт</h1>

        <div class="form-floating mb-3">
          {{ form.email(placeholder="name@example.ru") }} {{
          form.email.label(class="form-label") }}
        </div>

        <div class="form-floating mb-3">
          {{ form.password(placeholder="Пароль") }} {{
          form.password.label(class="form-label") }}
        </div>

        {{ form.submit }}
        <div class="p-2"></div>
        <p class="fs-6">
          Нет аккаунта?
          <a href="{{ url_for('user.registration') }}" class="link-primary"
            >Зарегистрироваться</a
          >
        </p>
        <p class="text-body-secondary">&copy; 2023</p>
      </form>
    </div>
  </div>
  <div class="hidden-xs col-sm-1 col-md-3 col-lg-4"></div>
</div>
{% endblock %}

webapp/templates/user/profile.html
{% extends "base.html" %}
{% block content %}
<div class="p-5"></div>
<h2> Логин: {{ user.email }} <br> Дата регистрации: {{ user.created_at }} </h2>
<p><a href="{{ url_for('user.logout') }}" class="link-primary">Выйти</a></p>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="hidden-xs col-sm-1 col-md-3 col-lg-4"></div>
    <div class="col-xs-12 col-sm-10 col-md-6 col-lg-4 text-center">
        <div class="p-5"></div>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <form action=" {{ url_for('user.process_reg') }}" method="POST">
                {{ form.hidden_tag() }}
                <h2>Регистрация</h2>
                <div class="p-2"></div>
                <div class="form-floating mb-3">
                    {{ form.name(placeholder="Имя") }}
                    {{ form.name.label(class="form-label") }}
                </div>
                <div class="form-floating mb-3">
                    {{ form.email(placeholder="name@example.ru") }}
                    {{ form.email.label(class="form-label") }}
                </div>
                <div class="form-floating mb-3">
                    {{ form.password(placeholder="Пароль") }}
                    {{ form.password.label(class="form-label") }}
                </div>
                <div class="form-floating mb-3">
                    {{ form.password2(placeholder="Повторите пароль") }}
                    {{ form.password2.label(class="form-label") }}
                </div>
                {{ form.submit }}
                <div class="p-2"></div>
                <p class="fs-6">Уже есть аккаунт? <br> <a href="{{ url_for('user.login') }}" class="link-primary">Войти</a>
                </p>
            </form>
        </div>
    </div>
    <div class="hidden-xs col-sm-1 col-md-3 col-lg-4"></div>
</div>
{% endblock %}