webapp/recipe/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from webapp.db import db, UNITS
from webapp.recipe.forms import AddRecipeForm
from webapp.recipe.models import (
    Ingredient,
    PRODUCT_CATEGORIES,
    Product,
    RECIPE_CATEGORIES,
    Recipe,
    RecipeDescription,
)
from webapp.shopping_list.forms import ChooseListForm
from webapp.shopping_list.models import ShoppingList
from webapp.utils import flash_errors_from_form, get_admin_id, object_does_not_exist
from uuid import uuid4

blueprint = Blueprint("recipe", __name__, url_prefix="/recipes")


@blueprint.route("/public")
def public_recipes():
    admin_id = get_admin_id()
    public_recipes = Recipe.query.filter(Recipe.user_id == admin_id).all()
    return render_template("recipe/public_recipes.html", public_recipes=public_recipes)


@blueprint.route("/my_recipes")
@login_required
def my_recipes():
    user_recipes = Recipe.query.filter(Recipe.user_id == current_user.id).all()
    return render_template("recipe/my_recipes.html", user_recipes=user_recipes)


@blueprint.route("/add_recipe", methods=["POST", "GET"])
@login_required
def add_recipe():
    form = AddRecipeForm()
    if request.method == "GET":
        return render_template("recipe/add_recipe.html", form=form)

    if form.validate_on_submit():
        name = form.name.data

        recipe_name_already_used = bool(
            Recipe.query.filter(
                Recipe.name == name, Recipe.user_id == current_user.id
            ).count()
        )
        if recipe_name_already_used:
            flash("Рецепт с таким именем уже существует", category="danger")
            return render_template("/recipe/add_recipe.html", form=form)

        category = form.category.data
        cooking_time = form.cooking_time.data

        recipe = Recipe(
            name=name,
            user_id=current_user.id,
            category=category,
            cooking_time=cooking_time,
        )
        db.session.add(recipe)
        db.session.commit()

        recipe = Recipe.query.filter(
            Recipe.name == recipe.name, Recipe.user_id == recipe.user_id
        ).one()

        return render_template(
            "recipe/add_ingredients&cooking_steps.html",
            recipe=recipe,
            PRODUCT_CATEGORIES=PRODUCT_CATEGORIES,
            RECIPE_CATEGORIES=RECIPE_CATEGORIES,
            UNITS=UNITS,
        )
    else:
        flash_errors_from_form(form)

    return redirect(url_for("recipe.my_recipes"))


@blueprint.route("/add_ingredient/<int:recipe_id>", methods=["POST"])
@login_required
def add_ingredient(recipe_id):
    recipe = Recipe.query.filter(Recipe.id == recipe_id).one_or_none()
    if not recipe:
        flash("При добавлении ингредиента произошла ошибка")
        return redirect(url_for("recipe.my_recipes"))

    product_name = request.form.get("product_name")
    product_category = request.form.get("product_category")
    ingredient_quantity = request.form.get("ingredient_quantity")
    ingredient_unit = request.form.get("ingredient_unit")

    if all([product_name, product_category, ingredient_quantity, ingredient_unit]):
        product = Product.query.filter(Product.name == product_name).one_or_none()

        if not product:
            product = Product(name=product_name, category=product_category)
            db.session.add(product)
            db.session.commit()
            product = Product.query.filter(Product.name == product_name).one()

        product_id = product.id

        quantity = ingredient_quantity

        ingredient = Ingredient(
            product_id=product_id,
            quantity=quantity,
            unit=ingredient_unit,
            recipe_id=recipe.id,
        )

        db.session.add(ingredient)
        db.session.commit()
        return "ok"

    else:
        return "failed"


@blueprint.route("/add_recipe_description/<int:recipe_id>", methods=["POST"])
def add_recipe_description(recipe_id):
    cooking_step_text = request.form.get("cooking_step_text")

    if cooking_step_text:
        cooking_step_obj = RecipeDescription(
            recipe_id=recipe_id, text=cooking_step_text
        )
        db.session.add(cooking_step_obj)
        db.session.commit()
        return "ok"

    else:
        return "failed"


@blueprint.route("/<int:recipe_id>")
def recipe(recipe_id):
    form = ChooseListForm()
    recipe = Recipe.query.filter(Recipe.id == recipe_id).one_or_none()
    if not recipe:
        return redirect(url_for("recipe.public_recipes"))

    admin_id = get_admin_id()

    current_user_id = None
    if current_user.is_authenticated:
        current_user_id = current_user.id

    if recipe.user_id != admin_id and recipe.user_id != current_user_id:
        flash("Этот рецепт Вам недоступен")
        return redirect(url_for("recipe.public_recipes"))

    elif current_user.is_authenticated:
        if not current_user.shopping_lists:
            new_shopping_list = ShoppingList(
                name="Мой список покупок",
                user_id=current_user.id,
                public_id=str(uuid4()),
            )
            db.session.add(new_shopping_list)
            db.session.commit()
        form.name.choices = [
            shopping_list.name for shopping_list in current_user.shopping_lists
        ]

    return render_template(
        "/recipe/recipe.html",
        PRODUCT_CATEGORIES=PRODUCT_CATEGORIES,
        RECIPE_CATEGORIES=RECIPE_CATEGORIES,
        recipe=recipe,
        form=form,
    )


@blueprint.route("/delete_recipe/<int:recipe_id>")
@login_required
def delete_recipe(recipe_id):
    recipe_to_delete = Recipe.query.filter(Recipe.id == recipe_id).one_or_none()

    if recipe_to_delete:
        db.session.delete(recipe_to_delete)
        db.session.commit()
        flash("Рецепт удалён.", category="success")

    return redirect(url_for("recipe.my_recipes"))


@blueprint.route("/copy_to_my_recipes/<int:recipe_id>")
@login_required
def copy_to_my_recipes(recipe_id):
    admin_id = get_admin_id()
    recipe = Recipe.query.filter(
        Recipe.id == recipe_id, Recipe.user_id == admin_id
    ).one_or_none()

    if recipe:
        if object_does_not_exist(Recipe, recipe.name):
            recipe_obj = Recipe(
                name=recipe.name,
                user_id=current_user.id,
                category=recipe.category,
                cooking_time=recipe.cooking_time,
            )
            db.session.add(recipe_obj)
            recipe_copy = Recipe.query.filter(
                Recipe.name == recipe.name, Recipe.user_id == current_user.id
            ).one()

            for ingredient in recipe.ingredients:
                ingredient_copy = Ingredient(
                    product_id=ingredient.product_id,
                    quantity=ingredient.quantity,
                    unit=ingredient.unit,
                    recipe_id=recipe_copy.id,
                )
                db.session.add(ingredient_copy)

            for step in recipe.description:
                step_copy = RecipeDescription(recipe_id=recipe_copy.id, text=step.text)
                db.session.add(step_copy)
            db.session.commit()

            flash("Рецепт успешно добавлен в Ваши рецепты", category="success")
            return redirect(url_for("recipe.recipe", recipe_id=recipe_copy.id))
    else:
        flash("Что-то пошло не так")

    return redirect(url_for("recipe.public_recipes"))

webapp/shopping_list/views.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from webapp.forms import RenameElement
from webapp.db import db
from webapp.recipe.models import Recipe
from webapp.shopping_list.forms import (
    AddShoppingItem,
    ChooseListForm,
    CreateListForm,
    EditQuantityOfShoppingItemForm,
)
from webapp.shopping_list.models import ShoppingItem, ShoppingList
from webapp.utils import (
    flash_errors_from_form,
    object_does_not_exist,
    update_item_to_shopping_list,
    update_recipe_to_shopping_list,
)
from uuid import uuid4
import json

blueprint = Blueprint("shopping_list", __name__, url_prefix="/shopping_lists")


@blueprint.route("/my-lists")
@login_required
def show_my_shopping_lists():
    session["redirect_url_after_renaming_shopping_list"] = url_for(
        "shopping_list.show_my_shopping_lists"
    )
    create_shopping_list_form = CreateListForm()
    rename_shopping_list_form = RenameElement()
    user = current_user
    user_shopping_lists = user.shopping_lists
    title = "Мои списки покупок"
    return render_template(
        "shopping_list/my_shopping_lists.html",
        create_shopping_list_form=create_shopping_list_form,
        rename_shopping_list_form=rename_shopping_list_form,
        user_shopping_lists=user_shopping_lists,
        page_title=title,
    )


@blueprint.route("/create-new-list", methods=["POST"])
def create_new_shopping_list():
    form = CreateListForm()
    public_id = str(uuid4())
    user = current_user

    if form.validate_on_submit():
        new_shopping_list_name = form.name.data.lower()

        if object_does_not_exist(ShoppingList, new_shopping_list_name):
            new_shopping_list = ShoppingList(
                name=new_shopping_list_name, user_id=user.id, public_id=public_id
            )
            db.session.add(new_shopping_list)
            db.session.commit()
            flash("Новый список успешно создан", category="success")
            return redirect(
                url_for("shopping_list.show_shopping_list", public_id=public_id)
            )

    else:
        flash_errors_from_form(form)

    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/delete-shopping-list/<shopping_list_id>")
def delete_shopping_list(shopping_list_id):
    shopping_list_to_delete = ShoppingList.query.filter(
        ShoppingList.id == shopping_list_id
    ).one_or_none()

    if shopping_list_to_delete:
        db.session.delete(shopping_list_to_delete)
        db.session.commit()
        flash("Список удалён", category="success")
    else:
        flash("При удалении списка возникла ошибка", category="danger")

    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/rename-shopping-list", methods=["POST"])
def rename_shopping_list():
    form = RenameElement()

    if form.validate_on_submit():
        new_name = form.new_value.data.lower()

        if object_does_not_exist(ShoppingList, new_name):
            shopping_list_id = form.element_id.data
            shopping_list_to_rename = ShoppingList.query.filter(
                ShoppingList.id == shopping_list_id
            ).one_or_none()

            if shopping_list_to_rename:
                shopping_list_to_rename.name = new_name
                db.session.commit()
                flash("Список переименован", category="success")
            else:
                flash("При переименовании списка возникла ошибка", category="danger")

    else:
        flash_errors_from_form(form)

    redirect_url = session.get(
        "redirect_url_after_renaming_shopping_list",
        url_for("shopping_list.show_my_shopping_lists"),
    )
    return redirect(redirect_url)


@blueprint.route("/my-lists/<public_id>")
def show_shopping_list(public_id):
    session["redirect_url_after_renaming_shopping_list"] = url_for(
        "shopping_list.show_shopping_list", public_id=public_id
    )

    add_shopping_item_form = AddShoppingItem()
    rename_shopping_list_form = RenameElement()
    edit_quantity_of_shopping_item_form = EditQuantityOfShoppingItemForm()

    shopping_list = ShoppingList.query.filter(
        ShoppingList.public_id == public_id
    ).one_or_none()

    if shopping_list:
        return render_template(
            "shopping_list/shopping_list.html",
            add_shopping_item_form=add_shopping_item_form,
            rename_shopping_list_form=rename_shopping_list_form,
            edit_quantity_of_shopping_item_form=edit_quantity_of_shopping_item_form,
            shopping_list=shopping_list,
        )

    flash("При показе списка возникла ошибка", category="danger")
    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/add-item/<shopping_list_public_id>", methods=["POST"])
def add_item_to_shopping_list(shopping_list_public_id):
    form = AddShoppingItem()

    if form.validate_on_submit():
        shopping_list = ShoppingList.query.filter(
            ShoppingList.public_id == shopping_list_public_id
        ).one_or_none()

        if shopping_list:
            update_item_to_shopping_list(
                shopping_list=shopping_list,
                name=form.name.data,
                quantity=form.quantity.data,
                unit=form.unit.data,
            )
            flash("Новый продукт успешно добавлен", category="success")

        else:
            flash("При добавлении продукта возникла ошибка", category="danger")
    else:
        flash_errors_from_form(form)

    return redirect(
        url_for("shopping_list.show_shopping_list", public_id=shopping_list_public_id)
    )


@blueprint.route("/delete-item/<shopping_list_public_id>/<item_id>")
def delete_item_from_shopping_list(shopping_list_public_id, item_id):
    item_to_delete = ShoppingItem.query.filter(ShoppingItem.id == item_id).one_or_none()

    if item_to_delete:
        db.session.delete(item_to_delete)
        db.session.commit()
        flash("Продукт удалён", category="success")
    else:
        flash("При удалении продукта возникла ошибка", category="danger")

    return redirect(
        url_for("shopping_list.show_shopping_list", public_id=shopping_list_public_id)
    )


@blueprint.route("/shopping-item-checkbox", methods=["POST"])
def shopping_item_checkbox():
    item_id = request.form.get("item_id")

    item_to_check = ShoppingItem.query.filter(ShoppingItem.id == item_id).one_or_none()

    if item_to_check:
        item_to_check.checked = int(request.form.get("state_of_checkbox"))
        db.session.commit()
        return "ok"
    else:
        return "failed"


@blueprint.route("/edit-quantity-of-shopping-item", methods=["POST"])
def edit_quantity_of_shopping_item():
    form = EditQuantityOfShoppingItemForm()

    if form.validate_on_submit():
        new_quantity = form.new_value.data
        shopping_item_id = form.element_id.data
        shopping_item_to_edit_quantity = ShoppingItem.query.filter(
            ShoppingItem.id == shopping_item_id
        ).one_or_none()

        if shopping_item_to_edit_quantity:
            shopping_item_to_edit_quantity.quantity = new_quantity
            db.session.commit()
            flash("Количество изменено", category="success")
        else:
            flash("При изменении количества возникла ошибка", category="danger")

    else:
        flash_errors_from_form(form)

    redirect_url = session.get(
        "redirect_url_after_renaming_shopping_list",
        url_for("shopping_list.show_my_shopping_lists"),
    )
    return redirect(redirect_url)


@blueprint.route("/add_recipe_to_shopping_list", methods=["POST"])
def add_recipe_to_shopping_list():
    form = ChooseListForm()

    shopping_lists = ShoppingList.query.filter(
        ShoppingList.user_id == current_user.id
    ).all()
    shopping_lists_names = [shopping_list.name for shopping_list in shopping_lists]
    form.name.choices = shopping_lists_names

    if form.validate_on_submit():
        chosen_shopping_list = ShoppingList.query.filter(
            ShoppingList.name == form.name.data,
            ShoppingList.user_id == current_user.id,
        ).one()
        recipe_info = json.loads(
            form.recipe_info.data.replace('"', '\\"').replace("'", '"')
        )
        recipe_id = recipe_info["id"]
        recipe = Recipe.query.get(recipe_id)
        portions = form.portions.data
        update_recipe_to_shopping_list(
            shopping_list=chosen_shopping_list, recipe=recipe, portions=portions
        )
        flash(
            f"Ингредиенты рецепта добавлены в список {chosen_shopping_list.name}",
            category="success",
        )
        return redirect(
            url_for(
                "recipe.recipe",
                recipe_id=recipe_id,
            )
        )

    else:
        flash_errors_from_form(form)
        return "failed"


@blueprint.route(
    "/choose_recipe_to_add/<shopping_list_public_id>", methods=["GET", "POST"]
)
def choose_recipe_to_add(shopping_list_public_id):
    user_recipes = Recipe.query.filter(Recipe.user_id == current_user.id).all()

    recipe_id = request.form.get("recipe_id")
    portions = request.form.get("portions")

    if recipe_id and portions:
        portions = int(portions)
        chosen_shopping_list = ShoppingList.query.filter(
            ShoppingList.public_id == shopping_list_public_id
        ).one()
        recipe = Recipe.query.get(recipe_id)
        update_recipe_to_shopping_list(
            shopping_list=chosen_shopping_list, recipe=recipe, portions=portions
        )

    return render_template(
        "shopping_list/choose_recipe_to_add.html",
        user_recipes=user_recipes,
        shopping_list_public_id=shopping_list_public_id,
    )

webapp/templates/recipe/add_ingredient.html
{% extends "base.html" %} {% block content %}
<div class="p space-for-messages"></div>

<h2>Этапы приготовления</h2>
<form class="add-cooking-step-form">
    <div class="new-cooking-step-input-group input-group mb-4">
        <span class="cooking-step-num input-group-text">1</span>
        <textarea class="new-cooking-step-text form-control" aria-label="With textarea" rows="3" required></textarea>
    </div>
    <button type="submit" class="add-cooking-step-button btn btn-primary" data-recipe-id='{{ recipe.id }}'>Добавить</button>
</form>

<h2>Ингредиенты</h2>
<form class="add-ingredient-form">
    <div class="new-ingredient-data row row-cols-xs-auto g-3 justify-content-md-center mb-3">
        <div class="cols-xs-auto col-md">
            <input class="product-name form-control" type="text" placeholder="Продукт" aria-label="default input example" required>
        </div>
        <div class="cols-xs-auto col-md-auto">
            <select class="product-category form-select" aria-label="Default select example" required>
                <option value="">Категория продукта</option>
                {% for category in PRODUCT_CATEGORIES.keys() %}
                    <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="cols-xs-auto col-md-auto">
            <input class='ingredient-quantity form-control' min="1" type="number" value="1">
        </div>
        <div class="cols-xs-auto col-md-auto">
            <select class="ingredient-unit form-select" aria-label="Default select example" required>
                <option value="">Единица измерения</option>
                {% for unit in UNITS %}
                    <option value="{{ unit }}">{{ unit }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
<button type="submit" class="add-ingredient-button btn btn-primary" data-recipe-id='{{ recipe.id }}'>Добавить</button>
</form>

<div class="p-2"></div>
<a class="btn btn-success w-100 py-2" href="{{ url_for('recipe.recipe', recipe_id=recipe.id) }}">
    Завершить и показать рецепт
</a>
{% endblock %}

webapp/templates/recipe/add_ingredients&cooking_steps.html
{% extends "base.html" %} {% block content %}
<div class="p space-for-messages"></div>

<h2>Этапы приготовления</h2>
<form class="add-cooking-step-form">
    <div class="new-cooking-step-input-group input-group mb-4">
        <span class="cooking-step-num input-group-text">1</span>
        <textarea class="new-cooking-step-text form-control" aria-label="With textarea" rows="3" required></textarea>
    </div>
    <button type="submit" class="add-cooking-step-button btn btn-primary" data-recipe-id='{{ recipe.id }}'>Добавить</button>
</form>

<h2>Ингредиенты</h2>
<form class="add-ingredient-form">
    <div class="new-ingredient-data row row-cols-xs-auto g-3 justify-content-md-center mb-3">
        <div class="cols-xs-auto col-md">
            <input class="product-name form-control" type="text" placeholder="Продукт" aria-label="default input example" required>
        </div>
        <div class="cols-xs-auto col-md-auto">
            <select class="product-category form-select" aria-label="Default select example" required>
                <option value="">Категория</option>
                {% for category in PRODUCT_CATEGORIES %}
                    <option value="{{ category }}">{{ PRODUCT_CATEGORIES[category][0] }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="cols-xs-auto col-md-auto">
            <input class='ingredient-quantity form-control' min="1" type="number" value="1">
        </div>
        <div class="cols-xs-auto col-md-auto">
            <select class="ingredient-unit form-select" aria-label="Default select example" required>
                <option value="">Единица измерения</option>
                {% for unit in UNITS %}
                    <option value="{{ unit }}">{{ unit }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
<button type="submit" class="add-ingredient-button btn btn-primary" data-recipe-id='{{ recipe.id }}'>Добавить</button>
</form>

<div class="p-2"></div>
<a class="btn btn-success w-100 py-2" href="{{ url_for('recipe.recipe', recipe_id=recipe.id) }}">
    Завершить и показать рецепт
</a>
{% endblock %}

webapp/templates/recipe/add_recipe.html
{% extends "base.html" %} {% block content %}
<form action=" {{ url_for('recipe.add_recipe') }}" method="POST">
  {{ form.hidden_tag() }}
  <h2>Создание рецепта</h2>
  <div class="p-2"></div>
  <div class="form-floating mb-3">
    {{ form.name(placeholder="Название") }}
    {{ form.name.label(class="form-label") }}
  </div>
  <div class="form mb-3">
    {{ form.category(placeholder="Категория рецепта") }}
  </div>
  <div class="form-floating mb-3">
    {{ form.cooking_time(placeholder="Время на приготовление") }} {{
    form.cooking_time.label(class="form-label") }}
  </div>
  <div class="form-floating mb-3">
    {{ form.servings(placeholder="Количество порций") }} {{
    form.servings.label(class="form-label") }}
  </div>
  {{ form.create }}
  <div class="p-2"></div>
</form>
{% endblock %}

webapp/templates/recipe/find_recipe_spoonacular.html
{% extends "base.html" %} {% block content %}
<div class="row justify-content-md-center">
    <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <form
                    action=" {{ url_for('recipe.find_recipes') }}"
                    method="POST">
                        <div class="row row-cols-xs-auto g-3 justify-content-md-center">
                        {{ form.csrf_token }}
                            <div class="cols-xs-auto col-md">
                                {{ form.name(placeholder="Название") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ form.category(placeholder="Категория") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ form.cuisine(placeholder="Кухня") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ form.diet(placeholder="Диета") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ form.search }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
<div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for recipe in recipes %}
    <div class="col">
        <div class="card h-100">
            <img src="{{ recipe['image'] }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ recipe['title'] }}</h5>
                <a href="{{ url_for('recipe.get_spoonacular_recipe_info', recipe_id = recipe['id'], recipe_title = recipe['title']) }}" class="stretched-link"></a>
            </div>
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}

webapp/templates/recipe/my_recipes.html
{% extends "base.html" %} {% block content %}
<div class="col-lg-8 mx-auto p-4 py-md-5">
  <h1 class="text-center">Мои рецепты</h1>
  <a
    class="btn btn-primary w-100 py-2 fs-3"
    href="{{ url_for('recipe.add_recipe', method='GET') }}"
  >
    Создать новый рецепт</a
  >
  <div class="p-3"></div>
  <table id="my_recipes" class="table table-striped fs-4">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Дата создания</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {%for recipe in user_recipes%}
      <tr>
        <td class="align-middle">
          <a
            href="{{ url_for('recipe.recipe', recipe_id = recipe.id) }}"
            class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover"
            >{{ recipe.name }}</a
          >
        </td>
        <td class="align-middle">
          {{ recipe.created_at.strftime("%d.%m.%Y") }}
        </td>
        <td>
          <a
            class="btn"
            role="button"
            href="{{
                   url_for('recipe.delete_recipe',
                   recipe_id = recipe.id)
                   }}"
            data-toggle="tooltip"
            data-placement="right"
            title="Удалить"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              class="bi bi-trash3"
              viewBox="0 0 16 16"
            >
              <path
                d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"
              />
            </svg>
          </a>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>

{% endblock %}

webapp/templates/recipe/recipe.html
{% extends "base.html" %} {% block content %} {% include 'recipe/static_recipe.html' %}
{% if current_user.is_authenticated %}

<div class="row">
  <div class="col"></div>
  <div class="col-5">
{% if recipe.user_id == current_user.id %}
    <button
      type="button"
      class="btn btn-primary"
      data-bs-toggle="modal"
      data-bs-target="#add_recipe_to_shopping_list"
    >
      Добавить ингредиенты в список покупок
    </button>
{% endif %}
{% if recipe.user_id != current_user.id %}
      <button class="copy-recipe btn btn-primary" data-recipe-info='{{ recipe }}' data-recipe-id ='{{ recipe["id"] }}'>Скопировать в мои рецепты</button>
{% endif %}
  </div>
  <div class="col"></div>
  <div
    class="modal fade create-new-list"
    id="add_recipe_to_shopping_list"
    tabindex="-1"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-body">
          <div class="col 12 text-center">
            <form
              action=" {{ url_for('shopping_list.add_recipe_to_shopping_list') }}"
              method="POST"
            >
              {{ form.csrf_token() }}
              {{ form.recipe_info(value=recipe) }}
              <div class="form-floating mb-3">
                {{ form.name(placeholder="Название списка") }}
                {{ form.name.label(class="form-label") }}
                <div class="form-floating mb-3">
                  {{ form.portions(placeholder="Количество порций") }} {{
                  form.portions.label(class="form-label") }}
                </div>
              </div>
              {{ form.submit }}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock %}

webapp/templates/recipe/static_recipe.html
<div class="col-lg-8 mx-auto p-4 py-md-5">
    <h1 class="text-center">{{ recipe.name }}</h1>
    <p class="fs-3 col-6 mx-auto text-center">{{ recipe.category }}</p>
    <p class="fw-bold fs-4">Время на приготовление:</p>
    <p class="fs-5 col-6 mx-auto">{{ recipe.cooking_time }} мин.</p>
    <p class="fw-bold fs-4">Описание</p>
    <ol class="list-group list-group-numbered list-group-flush">
        {% for step in recipe.description %}
        <li class="list-group-item fs-4">{{ step.text }}</li>
        {% endfor %}
    </ol>
    <p class="fw-bold fs-4">Для приготовления Вам потребуется:</p>
    <div class="col-6 mx-auto">
        <ol class="list-group list-group-flush">
            {% for ingredient in recipe.ingredients %}
            <li class="list-group-item fs-4">
                {{ ingredient }}
            </li>
            {% endfor %}
        </ol>
    </div>
</div>