webapp/shopping_list/models.py
from datetime import datetime
from webapp.db import db


class ShoppingList(db.Model):
    __tablename__ = "shopping_list"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    shopping_items = db.relationship(
        "ShoppingItem", backref="shopping_list", lazy=True, cascade="all, delete"
    )
    public_id = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class ShoppingItem(db.Model):
    __tablename__ = "shopping_item"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    category = db.Column(db.Text)
    shopping_list_id = db.Column(
        db.Integer, db.ForeignKey("shopping_list.id"), nullable=False
    )
    quantity = db.Column(db.Float)
    unit = db.Column(db.Text)
    checked = db.Column(db.Boolean, default=False)

webapp/shopping_list/forms.py
from flask_wtf import FlaskForm
from webapp.db import UNITS
from wtforms import (
    StringField,
    SubmitField,
    FloatField,
    SelectField,
    HiddenField,
    IntegerField,
)
from wtforms.validators import (
    DataRequired,
    NumberRange,
    Optional,
)


class CreateListForm(FlaskForm):
    name = StringField(
        "Название списка",
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField("Создать", render_kw={"class": "btn btn-primary"})


class AddShoppingItem(FlaskForm):
    name = StringField(
        "Название продукта",
        validators=[DataRequired()],
        render_kw={"class": "form-control", "id": "new_item_name"},
    )

    quantity = FloatField(
        "Количество",
        validators=[Optional(), NumberRange(min=0)],
        default=0,
        render_kw={"class": "form-control", "type": "number", "min": "0"},
    )

    unit = SelectField(
        "Единица измерения",
        choices=UNITS,
        validators=[DataRequired()],
        render_kw={"class": "form-select"},
    )

    submit = SubmitField("Добавить", render_kw={"class": "btn btn-primary"})


class EditQuantityOfShoppingItemForm(FlaskForm):
    new_value = FloatField(
        "Количество",
        validators=[Optional(), NumberRange(min=0)],
        render_kw={"class": "form-control"},
    )

    element_id = HiddenField(
        "element_id",
        validators=[DataRequired()],
        render_kw={"id": "element_id"},
    )

    submit = SubmitField("Изменить", render_kw={"class": "btn btn-primary"})


class ChooseListForm(FlaskForm):
    name = SelectField(
        "Добавить продукты из рецепта в список покупок",
        validators=[DataRequired()],
        coerce=str,
        render_kw={"class": "form-control"},
    )
    recipe_info = HiddenField(validators=[DataRequired()])
    portions = IntegerField(
        "Количество порций",
        validators=[DataRequired(), NumberRange(min=1)],
        default=1,
        render_kw={"class": "form-control"},
    )
    submit = SubmitField("Добавить", render_kw={"class": "btn btn-primary"})

webapp/shopping_list/views.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from webapp.forms import RenameElement
from webapp.db import db
from webapp.recipe.models import Recipe
from webapp.shopping_list.forms import (
    AddShoppingItem,
    ChooseListForm,
    CreateListForm,
    EditQuantityOfShoppingItemForm,
)
from webapp.shopping_list.models import ShoppingItem, ShoppingList
from webapp.utils import (
    flash_errors_from_form,
    object_does_not_exist,
    update_item_to_shopping_list,
    update_recipe_to_shopping_list,
)
from uuid import uuid4
import json

blueprint = Blueprint("shopping_list", __name__, url_prefix="/shopping_lists")


@blueprint.route("/my-lists")
@login_required
def show_my_shopping_lists():
    session["redirect_url_after_renaming_shopping_list"] = url_for(
        "shopping_list.show_my_shopping_lists"
    )
    create_shopping_list_form = CreateListForm()
    rename_shopping_list_form = RenameElement()
    user = current_user
    user_shopping_lists = user.shopping_lists
    title = "Мои списки покупок"
    return render_template(
        "shopping_list/my_shopping_lists.html",
        create_shopping_list_form=create_shopping_list_form,
        rename_shopping_list_form=rename_shopping_list_form,
        user_shopping_lists=user_shopping_lists,
        page_title=title,
    )


@blueprint.route("/create-new-list", methods=["POST"])
def create_new_shopping_list():
    form = CreateListForm()
    public_id = str(uuid4())
    user = current_user

    if form.validate_on_submit():
        new_shopping_list_name = form.name.data.lower()

        if object_does_not_exist(ShoppingList, new_shopping_list_name):
            new_shopping_list = ShoppingList(
                name=new_shopping_list_name, user_id=user.id, public_id=public_id
            )
            db.session.add(new_shopping_list)
            db.session.commit()
            flash("Новый список успешно создан", category="success")
            return redirect(
                url_for("shopping_list.show_shopping_list", public_id=public_id)
            )

    else:
        flash_errors_from_form(form)

    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/delete-shopping-list/<shopping_list_id>")
def delete_shopping_list(shopping_list_id):
    shopping_list_to_delete = ShoppingList.query.filter(
        ShoppingList.id == shopping_list_id
    ).one_or_none()

    if shopping_list_to_delete:
        db.session.delete(shopping_list_to_delete)
        db.session.commit()
        flash("Список удалён", category="success")
    else:
        flash("При удалении списка возникла ошибка", category="danger")

    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/rename-shopping-list", methods=["POST"])
def rename_shopping_list():
    form = RenameElement()

    if form.validate_on_submit():
        new_name = form.new_value.data.lower()

        if object_does_not_exist(ShoppingList, new_name):
            shopping_list_id = form.element_id.data
            shopping_list_to_rename = ShoppingList.query.filter(
                ShoppingList.id == shopping_list_id
            ).one_or_none()

            if shopping_list_to_rename:
                shopping_list_to_rename.name = new_name
                db.session.commit()
                flash("Список переименован", category="success")
            else:
                flash("При переименовании списка возникла ошибка", category="danger")

    else:
        flash_errors_from_form(form)

    redirect_url = session.get(
        "redirect_url_after_renaming_shopping_list",
        url_for("shopping_list.show_my_shopping_lists"),
    )
    return redirect(redirect_url)


@blueprint.route("/my-lists/<public_id>")
def show_shopping_list(public_id):
    session["redirect_url_after_renaming_shopping_list"] = url_for(
        "shopping_list.show_shopping_list", public_id=public_id
    )

    add_shopping_item_form = AddShoppingItem()
    rename_shopping_list_form = RenameElement()
    edit_quantity_of_shopping_item_form = EditQuantityOfShoppingItemForm()

    shopping_list = ShoppingList.query.filter(
        ShoppingList.public_id == public_id
    ).one_or_none()

    if shopping_list:
        return render_template(
            "shopping_list/shopping_list.html",
            add_shopping_item_form=add_shopping_item_form,
            rename_shopping_list_form=rename_shopping_list_form,
            edit_quantity_of_shopping_item_form=edit_quantity_of_shopping_item_form,
            shopping_list=shopping_list,
        )

    flash("При показе списка возникла ошибка", category="danger")
    return redirect(url_for("shopping_list.show_my_shopping_lists"))


@blueprint.route("/add-item/<shopping_list_public_id>", methods=["POST"])
def add_item_to_shopping_list(shopping_list_public_id):
    form = AddShoppingItem()

    if form.validate_on_submit():
        shopping_list = ShoppingList.query.filter(
            ShoppingList.public_id == shopping_list_public_id
        ).one_or_none()

        if shopping_list:
            update_item_to_shopping_list(
                shopping_list=shopping_list,
                name=form.name.data,
                quantity=form.quantity.data,
                unit=form.unit.data,
            )
            flash("Новый продукт успешно добавлен", category="success")

        else:
            flash("При добавлении продукта возникла ошибка", category="danger")
    else:
        flash_errors_from_form(form)

    return redirect(
        url_for("shopping_list.show_shopping_list", public_id=shopping_list_public_id)
    )


@blueprint.route("/delete-item/<shopping_list_public_id>/<item_id>")
def delete_item_from_shopping_list(shopping_list_public_id, item_id):
    item_to_delete = ShoppingItem.query.filter(ShoppingItem.id == item_id).one_or_none()

    if item_to_delete:
        db.session.delete(item_to_delete)
        db.session.commit()
        flash("Продукт удалён", category="success")
    else:
        flash("При удалении продукта возникла ошибка", category="danger")

    return redirect(
        url_for("shopping_list.show_shopping_list", public_id=shopping_list_public_id)
    )


@blueprint.route("/shopping-item-checkbox", methods=["POST"])
def shopping_item_checkbox():
    item_id = request.form.get("item_id")

    item_to_check = ShoppingItem.query.filter(ShoppingItem.id == item_id).one_or_none()

    if item_to_check:
        item_to_check.checked = int(request.form.get("state_of_checkbox"))
        db.session.commit()
        return "ok"
    else:
        return "failed"


@blueprint.route("/edit-quantity-of-shopping-item", methods=["POST"])
def edit_quantity_of_shopping_item():
    form = EditQuantityOfShoppingItemForm()

    if form.validate_on_submit():
        new_quantity = form.new_value.data
        shopping_item_id = form.element_id.data
        shopping_item_to_edit_quantity = ShoppingItem.query.filter(
            ShoppingItem.id == shopping_item_id
        ).one_or_none()

        if shopping_item_to_edit_quantity:
            shopping_item_to_edit_quantity.quantity = new_quantity
            db.session.commit()
            flash("Количество изменено", category="success")
        else:
            flash("При изменении количества возникла ошибка", category="danger")

    else:
        flash_errors_from_form(form)

    redirect_url = session.get(
        "redirect_url_after_renaming_shopping_list",
        url_for("shopping_list.show_my_shopping_lists"),
    )
    return redirect(redirect_url)


@blueprint.route("/add_recipe_to_shopping_list", methods=["POST"])
def add_recipe_to_shopping_list():
    form = ChooseListForm()

    shopping_lists = ShoppingList.query.filter(
        ShoppingList.user_id == current_user.id
    ).all()
    shopping_lists_names = [shopping_list.name for shopping_list in shopping_lists]
    form.name.choices = shopping_lists_names

    if form.validate_on_submit():
        chosen_shopping_list = ShoppingList.query.filter(
            ShoppingList.name == form.name.data,
            ShoppingList.user_id == current_user.id,
        ).one()
        recipe_info = json.loads(
            form.recipe_info.data.replace('"', '\\"').replace("'", '"')
        )
        recipe_id = recipe_info["id"]
        recipe = Recipe.query.get(recipe_id)
        portions = form.portions.data
        update_recipe_to_shopping_list(
            shopping_list=chosen_shopping_list, recipe=recipe, portions=portions
        )
        flash(
            f"Ингредиенты рецепта добавлены в список {chosen_shopping_list.name}",
            category="success",
        )
        return redirect(
            url_for(
                "recipe.recipe",
                recipe_id=recipe_id,
            )
        )

    else:
        flash_errors_from_form(form)
        return "failed"


@blueprint.route(
    "/choose_recipe_to_add/<shopping_list_public_id>", methods=["GET", "POST"]
)
def choose_recipe_to_add(shopping_list_public_id):
    user_recipes = Recipe.query.filter(Recipe.user_id == current_user.id).all()

    recipe_id = request.form.get("recipe_id")
    portions = request.form.get("portions")

    if recipe_id and portions:
        portions = int(portions)
        chosen_shopping_list = ShoppingList.query.filter(
            ShoppingList.public_id == shopping_list_public_id
        ).one()
        recipe = Recipe.query.get(recipe_id)
        update_recipe_to_shopping_list(
            shopping_list=chosen_shopping_list, recipe=recipe, portions=portions
        )

    return render_template(
        "shopping_list/choose_recipe_to_add.html",
        user_recipes=user_recipes,
        shopping_list_public_id=shopping_list_public_id,
    )

webapp/templates/shopping_list/choose_recipe_to_add.html
{% extends "base.html" %}

{% block content %}
<div class="p-1 text-center space-for-messages"></div>
<div class="row">
    <div class="col-auto text-start">
        <a href="{{ url_for('shopping_list.show_shopping_list', public_id=shopping_list_public_id) }}"
           class="btn btn-primary"
           role="button">
            <i class="bi bi-arrow-left"></i>
            Вернуться к списку
        </a>
    </div>
</div>
<div class="p-2"></div>
{% if user_recipes|length == 0 %}
    <div class="row">
        <div class="p-4"></div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4 text-center">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">У Вас пока нет своих рецептов</h5>
                <div class="p-1"></div>
                <a href="{{ url_for('add_recipe') }}" class="btn btn-primary">Добавить свой рецепт</a>
                <a href="{{ url_for('recipes') }}" class="btn btn-primary">Подобрать рецепт на сайте</a>
              </div>
            </div>
        </div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
    </div>
{% endif %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for recipe in user_recipes %}
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
                <p class="card-text">
                    {% for ingredient in recipe.ingredients %}
                        {{ ingredient }}<br>
                    {%endfor%}
                </p>
                <div class="row justify-content-md-center">
                    <div class="col-8">
                        <div class="input-group mb-3">
                            <span class="input-group-text">Кол-во порций</span>
                            <input id="select_portions_{{ recipe.id }}" min="1" type="number" value="1"
                                   class="form-control"/>
                        </div>
                    </div>
                    <div class="col-4 text-start">
                        <a class="btn btn-danger add-ingredients-from-recipe"
                           id={{recipe.id}}
                           data-recipe-id='{{ recipe.id }}'
                           data-shopping-list-public-id="{{ shopping_list_public_id }}"
                           role="button"
                           data-placement="right"
                           title="Добавить">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                                <path class='svg-path'
                                      d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}

webapp/templates/shopping_list/my_shopping_lists.html
{% extends "base.html" %}
{% import "edit_button_and_modal_form.html" as edit_shopping_list_name %}

{% block content %}
<div class="row">
    <div class="hidden-xs col-sm-2 col-md-3 col-lg-3"></div>
    <div class="col-sm-8 col-md-6 col-lg-5">
        <h2>Мои списки покупок</h2>
        <div class="p-2"></div>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#create_new_list">
            Создать новый список
        </button>
        <div class="p-3"></div>
        <table id='my_shopping_lists' class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Имя</th>
                <th scope="col"></th>
                <th scope="col">Создан</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {%for list in user_shopping_lists%}
            <tr>
                <td class="align-middle">
                    <a href="{{ url_for('shopping_list.show_shopping_list', public_id = list.public_id) }}"
                       class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">
                       {{list.name }}
                    </a>
                </td>
                <td>
                    {{ edit_shopping_list_name.button(
                        button_id='rename_shopping_list_button',
                        modal_id='rename_shopping_list_modal',
                        element_id=list.id
                    )}}
                </td>
                <td class="align-middle">{{ list.created_at.strftime("%d.%m.%Y") }}</td>
                <td>
                    <a class="btn"
                       role="button"
                       onclick="copy_link_to_clipboard('/{{list.public_id}}','#copy_button_{{list.id}}')"
                       id="copy_button_{{list.id}}"
                       data-toggle="tooltip"
                       data-placement="right"
                       title="Копировать ссылку">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-link" viewBox="0 0 16 16">
                            <path d="M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-4H9c-.086 0-.17.01-.25.031A2 2 0 0 1 7 10.5H4a2 2 0 1 1 0-4h1.535c.218-.376.495-.714.82-1z"/>
                            <path d="M9 5.5a3 3 0 0 0-2.83 4h1.098A2 2 0 0 1 9 6.5h3a2 2 0 1 1 0 4h-1.535a4.02 4.02 0 0 1-.82 1H12a3 3 0 1 0 0-6H9z"/>
                        </svg>
                    </a>
                </td>
                <td>
                    <a class="btn"
                       role="button"
                       href="{{
                                       url_for('shopping_list.delete_shopping_list',
                                       shopping_list_id = list.id)
                                       }}"
                       data-toggle="tooltip"
                       data-placement="right"
                       title="Удалить">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                             fill="currentColor"
                             class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg>
                    </a>
                </td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>
    <div class="hidden-xs col-sm-2 col-md-3 col-lg-4"></div>
</div>
<div class="modal fade create-new-list" id="create_new_list" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="col 12 text-center">
                    <form action=" {{ url_for('shopping_list.create_new_shopping_list') }}" method="POST">
                        {{ create_shopping_list_form.csrf_token }}
                        <div class="form-floating mb-3">
                            {{ create_shopping_list_form.name(placeholder="Название списка") }}
                            {{ create_shopping_list_form.name.label(class="form-label") }}
                        </div>
                        {{ create_shopping_list_form.submit }}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{{ edit_shopping_list_name.modal_form(
    modal_id='rename_shopping_list_modal',
    edit_form=rename_shopping_list_form,
    edit_form_url=url_for("shopping_list.rename_shopping_list")
)}}
{% endblock %}

webapp/templates/shopping_list/shopping_list.html
{% extends "base.html" %}
{% import "edit_button_and_modal_form.html" as edit_feature %}

{% block content %}
<div class="p-2"></div>
<div class="row">
    <div class="row align-items-center">
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4">
            <div class="row align-items-center">
                <div class="col-auto text-end">
                    <h2>{{ shopping_list.name }}</h2>
                </div>
                <div class="col-auto text-start">
                    {{ edit_feature.button(
                        button_id='rename_shopping_list_button',
                        element_id=shopping_list.id,
                        modal_id='rename_shopping_list_modal'
                        )
                    }}
                </div>
                {{ edit_feature.modal_form(
                    modal_id='rename_shopping_list_modal',
                    edit_form=rename_shopping_list_form,
                    edit_form_url=url_for("shopping_list.rename_shopping_list")
                    )
                }}
            </div>
        </div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
    </div>
    <div class="row">
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4">
            <p class="fw-light text-start">
                Создан: {{ shopping_list.created_at.strftime("%d.%m.%Y %H:%M ") }}
            </p>
        </div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
    </div>
    <div class="row justify-content-md-center">
            <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
                <div class="col-sm-8 col-md-8 col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <form class="add-item-form"
              action=" {{ url_for('shopping_list.add_item_to_shopping_list', shopping_list_public_id = shopping_list.public_id) }}"
              method="POST">
                        <div class="row row-cols-xs-auto g-3 justify-content-md-center">

            {{ add_shopping_item_form.csrf_token }}
                            <div class="cols-xs-auto col-md">
                                {{ add_shopping_item_form.name(placeholder="Продукт") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ add_shopping_item_form.quantity(placeholder="Количество") }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ add_shopping_item_form.unit() }}
                            </div>
                            <div class="cols-xs-auto col-md-auto">
                                {{ add_shopping_item_form.submit }}
                            </div>

                            </div>
                            </form>
                        </div>
                    </div>
                    </div>
                <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>

    </div>
    <div class="p-2"></div>
    <div class="row justify-content-md-center">
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4">
            <a href="{{ url_for('shopping_list.choose_recipe_to_add', shopping_list_public_id = shopping_list.public_id) }}"
               class="btn btn-primary btn-block w-100">
               Добавить ингредиенты из рецепта
            </a>
        </div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
    </div>
    <div class="p-2 text-center space-for-messages"></div>
    <div class="row justify-content-md-center">
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
        <div class="col-sm-8 col-md-8 col-lg-4">
            <ul class="list-group shopping-list">
                {% for item in shopping_list.shopping_items|sort(attribute="checked,name") %}
                <li class="list-group-item shopping-list-item">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <input data-id="{{ item.id }}"
                                   class="form-check-input me-1 check-item"
                                   type="checkbox" value="" id="check_item_{{ item.id }}"
                                   {%if item.checked %} checked="checked" {% endif %}
                            >
                            <label
                                    class="form-check-label {%if item.checked %} text-decoration-line-through {% endif %} item-name"
                                    for="check_item_{{ item.id }}">{{ item.name }}
                            </label>
                        </div>
                        <div class="col-3 text-end">
                            <span class="align-middle">{%if item.quantity != 0 %}{{ item.quantity }} {{ item.unit }}{% endif %}</span>
                        </div>
                        <div class="col-1 text-end">
                            {{edit_feature.button(
                                button_id='edit_quantity',
                                modal_id='edit_quantity_modal',
                                element_id=item.id
                                )
                            }}
                        </div>
                        {{ edit_feature.modal_form(
                            modal_id = 'edit_quantity_modal',
                            edit_form=edit_quantity_of_shopping_item_form,
                            edit_form_url=url_for("shopping_list.edit_quantity_of_shopping_item")
                            )
                        }}
                        <div class="col-2 text-end">
                            <a class="btn"
                               href="{{
                                       url_for('shopping_list.delete_item_from_shopping_list',
                                       item_id = item.id,
                                       shopping_list_public_id = shopping_list.public_id)
                                       }}"
                               role="button"
                               data-toggle="tooltip"
                               data-placement="right"
                               title="Удалить">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     width="16"
                                     height="16"
                                     fill="currentColor"
                                     class="bi bi-trash3"
                                     viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </li>
                {%endfor%}
            </ul>
        </div>
        <div class="hidden-xs col-sm-2 col-md-2 col-lg-4"></div>
    </div>
</div>
{% endblock %}